// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sihajnfjiadejqupyrxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpaGFqbmZqaWFkZWpxdXB5cnh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTU5OTMsImV4cCI6MjA3MjE5MTk5M30.LQzIysx_qBO3y80VJ7a8Gk1VfZoTSajjLhjfY3Envgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});